### ISSUE TITLE
panic running termbox

### ISSUE THREAD

**Issue by techtonik** [nsf/termbox-go#106]
I am accessing bash from custom client remotely over websocket, and termbox fails to run in this session.
```
# go run _demos/keyboard.go
panic: termbox: error while reading terminfo data: termbox: TERM environment variable not set

goroutine 1 [running]:
main.main()
        /root/go/src/github.com/nsf/termbox-go/_demos/keyboard.go:654 +0x74

goroutine 5 [runnable]:
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:20
created by os/signal.init.1
        /usr/lib/go/src/os/signal/signal_unix.go:28 +0x37
exit status 2
```

**Comment by nsf** [comment]
Well, the panic says what it says. TERM environment variable is not set. You can't use termbox without this environment variable. You can set it artificially if you know what you're doing or normally a terminal emulator sets it for you. As for your problem in general, I'm not sure I understand what are you doing and what do you want and frankly I'm not interested at all.

**Comment by techtonik** [comment]
@nsf who sets this variable? is there any common default?

**Comment by nsf** [comment]
You can use "xterm" as default.

**Comment by techtonik** [comment]
Why `termbox` can not choose the default?

**Comment by nsf** [comment]
Because it's a good way to show that something is wrong with the environment you're running termbox app on. And if I just assume xterm and it starts silently breaking everywhere, that's not good.

**Comment by techtonik** [comment]
"something is wrong" is not very helpful message. =) Why it is not possible to assume `xterm` non-silently? Can `termbox` give an explanation why TERM is needed at all and who should set it?

**Comment by nsf** [comment]
Termbox apps work in terminal environments. All terminal environments provide TERM environment variable. I can make a message better.

**Comment by techtonik** [comment]
Better message would be cool, indeed. This still doesn't explain why TERM is needed and who should set it. How can I say that my remote console (which is running bash) is not terminal?

**Comment by nsf** [comment]
Have no idea.

**Comment by samizzo** [comment]
I think the error message is perfectly adequate. It describes the problem exactly: a missing TERM variable. @techtonik I think you're missing some key pieces of information. It sounds like you are essentially writing a TELNET client, which means that YOU need to provide the terminal type to the server as part of the protocol connection negotiation.

**Comment by techtonik** [comment]
@samizzo all this TELNET + termios + pty + TTY + terminal stuff is way too confusing. I wish that somebody could make a diagram of why it has to be so complicated in this way.
