### ISSUE TITLE
Init fails with io.EOF on darwin

### ISSUE THREAD

**Issue by rakyll** [nsf/termbox-go#80]
I am a termui user and my termbox.Init is failing with the following error:

```
termbox: error while reading terminfo data: EOF
```

The EOF is coming from ti_read_string where you read rd, even though it successfully seeks to the offset.

```
func ti_read_string(rd *bytes.Reader, str_off, table int16) (string, error) {
var off int16
_, err := rd.Seek(int64(str_off), 0)
if err != nil {
    return "", err
}
err = binary.Read(rd, binary.LittleEndian, &off)
if err != nil {
    // err is io.EOF
    return "", err
}
```

**Comment by nsf** [comment]
Interesting, the only thing I can offer right now is to add the code which tries to fallback to built-in database when reading a terminfo file which cannot be parsed by termbox. 

Because, well, you have that terminfo file which is somehow incompatible with what termbox thinks about terminfo files. You can investigate it further, but that means reading this binary file manually with hex editor, figuring out the offset where ti_read_string fails and seeing what the heck is wrong there.

Or you can track down the file termbox opens and upload it and I'll do that for you.

**Comment by demizer** [comment]
I ran into this problem with trying to run the examples using "go run".

My environment:

* Go 1.5 Beta 1
* TERM=xterm-256color
* Arch Linux

Upstream issue: https://github.com/golang/go/issues/11449

``os.Getenv("TERM")`` returns "dumb" despite the running terminal being xterm-256color.

Parent loop where failure occurs: https://github.com/nsf/termbox-go/blob/master/terminfo.go#L163
Failure point: https://github.com/nsf/termbox-go/blob/master/terminfo.go#L189

```console
$ go run _demos/editbox.go
os.Getenv() == dumb
terminfo path: /usr/share/terminfo/d/dumb
Loop: 0 str_offset+2*ti_keys[i]: 172
Loop: 1 str_offset+2*ti_keys[i]: 176
Loop: 2 str_offset+2*ti_keys[i]: 178
Loop: 3 str_offset+2*ti_keys[i]: 180
Loop: 4 str_offset+2*ti_keys[i]: 182
Loop: 5 str_offset+2*ti_keys[i]: 184
Loop: 6 str_offset+2*ti_keys[i]: 186
Loop: 7 str_offset+2*ti_keys[i]: 188
Loop: 8 str_offset+2*ti_keys[i]: 190
Loop: 9 str_offset+2*ti_keys[i]: 174
Loop: 10 str_offset+2*ti_keys[i]: 472
panic: termbox: error while reading terminfo data: EOF

goroutine 1 [running]:
main.main()
	/home/demizer/src/github.com/nsf/termbox-go/_demos/editbox.go:258 +0x65

goroutine 5 [syscall]:
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/lib/go/src/os/signal/signal_unix.go:28 +0x37
exit status 2
```

A hexdump of the terminfo file:

```console
$ hexdump /usr/share/terminfo/d/dumb
0000000 011a 0018 0002 0001 0082 0008 7564 626d
0000010 387c 2d30 6f63 756c 6e6d 6420 6d75 2062
0000020 7474 0079 0100 0050 ffff 0000 0002 ffff
0000030 ffff ffff ffff ffff ffff ffff ffff 0004
0000040 ffff ffff ffff ffff ffff ffff ffff ffff
*
0000120 ffff ffff ffff ffff ffff 0006 0007 000d
0000130 000a 000a                              
0000134
```

For now, my work around is to manually set ```os.Getenv``` calls to xterm.

**Comment by nsf** [comment]
I guess we need a better terminfo parser, I'll look into it when I have free time.

**Comment by misterunix** [comment]
I hope this helps.


[bjones@develop go]$ set | grep "TERM"
TERM=xterm

[bjones@develop go]$ cat o.go
package main

import "os"
import "fmt"

func main() {
  r := os.Getenv("TERM")
  fmt.Println(r)
}

[bjones@develop go]$ go run o.go
dumb

Change in grid.go to make demo work:
func main() {
        os.Setenv("TERM","xterm")

I would bet that dumb is not complete and you are looking for features that are not there.

From the Terminfo data
16.3 Bugs in Existing Terminfo Files (and Hardware)

Unfortunately, there are a number of bugs in the terminfo and termcap files. In addition, many of these terminfo files are incomplete and do not define certain features available on the terminals. Sometimes you can get by without modifying the terminfo but in other cases you need to modify it or possibly use another emulation that has a good terminfo.

The sad state of the supplied terminfo files is due to a number of reasons. One is that during the 1980's when many of them were written (often in termcap format), application programs did not utilize more advanced terminal features. Thus if such feature were not in the termcap (or terminfo) file, no one complained. Also, writing termcaps was often done by volunteers who were in short supply. Today, programs such as vim use "context highlighting" and minicom uses the terminal's graphics character set. These often need more definitions to be added to the old termcap. This may (or may not) have already been done.

Most terminals had hardware bugs (in their firmware) and sometimes these were "fixed" by modifying the termcap. Then the manufacturer might send out replacement chips which would fix the bug. Not all owners would bother to get the replacement chips. Thus there may be 2 or more terminfos for your terminal, depending on what firmware chips it has in it. This situation was often not noted in the termcap and only one of these termcaps may be supplied with Linux. Some hardware bugs which existed for features that were almost never used in the past likely never did get fixed. Also, some reported hardware bugs may never have been fixed since they were not of much significance at the time or because the terminal manufacturing company went out of business, etc.

**Comment by ericwq** [comment]
os.Setenv("TERM","xterm") 
does solve my problem. i got problem with go test. but no problem with go run.

**Comment by ericwq** [comment]
for go test , os.Getenv("TERM") return dumb. that's the reason. the 11449 only solve the go run problem.
